# Generated by Django 6.0.1 on 2026-01-31 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meds', '0002_prescription_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meds.source'),
        ),
    ]
